### ISSUE TITLE
action-decorators: TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Turbo87** [lennyburdette/ember-action-codemods#1]
I tried to run the `action-decorators` codemod on our codebase but a few files failed with the following error:
```
TypeError: Cannot read property 'name' of undefined
    at isActionsHash (/private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/jscodeshift119914-33518-jsfuua.4uejq:82:14)
    at Array.find (<anonymous>)
    at NodePath.ast.find.replaceWith.path (/private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/jscodeshift119914-33518-jsfuua.4uejq:10:45)
    at NodePath.<anonymous> (/Users/tbieniek/.config/yarn/global/node_modules/jscodeshift/src/collections/Node.js:144:47)
    at __paths.forEach (/Users/tbieniek/.config/yarn/global/node_modules/jscodeshift/src/Collection.js:77:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/tbieniek/.config/yarn/global/node_modules/jscodeshift/src/Collection.js:76:18)
    at Collection.replaceWith (/Users/tbieniek/.config/yarn/global/node_modules/jscodeshift/src/collections/Node.js:142:17)
    at Collection.typedMethod [as replaceWith] (/Users/tbieniek/.config/yarn/global/node_modules/jscodeshift/src/Collection.js:415:43)
    at transformer (/private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/jscodeshift119914-33518-jsfuua.4uejq:9:32)
```

**Comment by lennyburdette** [comment]
Do you have a code sample I could use to create a test case? My app already uses action decorators so I haven't tested this one thoroughly.
